### ISSUE TITLE
optimize for social media

### ISSUE THREAD

**Issue by ollehints** [geocollections/kivid2#24]
Each rock page should be easily citable in FB, Twitter and Instagram. And they should look nice from there: showing the title, rock name, 1-3 images and description. Currently only the title is shown in FB:
![image](https://user-images.githubusercontent.com/14974887/52479655-09cb4400-2bb2-11e9-949c-9afbce85e59a.png)

**Comment by OlesjaSenkiv** [comment]
Currently facebook cannot identify dynamically created meta tags this means each rock page couldn't be citable as we expect. The only solution is to use SSR but we decided to not use it. Some explanation could be found here https://github.com/nuxt/vue-meta/issues/133.
