### ISSUE TITLE
cookie warning

### ISSUE THREAD

**Issue by ollehints** [geocollections/kivid2#25]
we should display a warning on the bottom of page that we use cookies for page functionality and usage statistics and that if user continues on the site he/she accepts this. should have a checkbox that saves an eternal cookie that prevents showing the warning next time.

**Comment by OlesjaSenkiv** [comment]
Main functionality is implimented but Cookie Policy, Privacy Policy, and our Terms of Service should be placed to geokogud or geocollection, so that user  could read it.

**Comment by ollehints** [comment]
https://api.geocollections.info/page/67
https://api.geocollections.info/page/68
https://api.geocollections.info/page/69
