### ISSUE TITLE
page footer update

### ISSUE THREAD

**Issue by ollehints** [geocollections/kivid2#26]
Page footer should be extended. Add:
- License conditions
- Hosting information 
- NATARC logo
- EU logo
- Logos of content providing institutions: TalTech, TU, ELM

**Comment by OlesjaSenkiv** [comment]
The following logos are required:  TalTech, TU, ELM

**Comment by ollehints** [comment]
I will do this, have a version already not yet committed

![image](https://user-images.githubusercontent.com/14974887/52712174-7b353900-2f9c-11e9-8555-0a1839458010.png)

**Comment by ollehints** [comment]
footer and the cookie message still need styling adjustments. currently they are not working well with small screens.

**Comment by ollehints** [comment]
done
