### ISSUE TITLE
advanced search by range

### ISSUE THREAD

**Issue by ollehints** [geocollections/kivid2#30]
If searching by numeric range of a property, too many results are returned. Compare two searches: hardness more than 8, and hardness between 8 and 9. Correct query should match all rocks where either value_min or value_max is between the user values. Easiest to use would be _range filter for API call.

**Comment by OlesjaSenkiv** [comment]
> Easiest to use would be _range filter for API call.

Yes it could be used if we had only one parameter but current search functionality also supports multiple parameters (add rows).
